// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gdrequests_api.Data;

#nullable disable

namespace gdrequests_api.Migrations
{
    [DbContext(typeof(MainDataContext))]
    [Migration("20220914090205_Levels -> Requests")]
    partial class LevelsRequests
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("gdrequests_api.Data.Entities.LevelMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDemon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEpic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("LevelMetadata");
                });

            modelBuilder.Entity("gdrequests_api.Data.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("strftime('%s', 'now')");

                    b.Property<int>("LevelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("LevelId")
                        .IsUnique();

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("gdrequests_api.Data.Entities.LevelMetadata", b =>
                {
                    b.HasOne("gdrequests_api.Data.Entities.Request", "Request")
                        .WithOne("Metadata")
                        .HasForeignKey("gdrequests_api.Data.Entities.LevelMetadata", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("gdrequests_api.Data.Entities.Request", b =>
                {
                    b.Navigation("Metadata")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
